# Generated by Django 5.0.6 on 2024-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('links', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_used', models.ManyToManyField(to='api.tech')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
